wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1680208658.082211
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.7.11
      5: 0.14.0
      8:
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
